import assert from 'node:assert/strict'
import { test } from 'node:test'
import { localizeActivityText, matchActivityTemplate, templatePattern } from '../src/lib/activityText.ts'
import { operations } from '../src/locales/operations.ts'

// One real sample per server template, written the way the Go code formats it
// (internal/handlers, internal/db, internal/runner), with its English rendering.
const SAMPLES = {
  agentLaunchAction: ["Exécution de clarify sur l'agent local", 'Running clarify on the local agent'],
  agentLaunchSummary: ["Exécution en cours sur l'agent local (mbp-seb)", 'Running on the local agent (mbp-seb)'],
  agentLaunchDelegated: ["Déléguée à l'agent local (mbp-seb)...", 'Delegated to the local agent (mbp-seb)...'],
  targetTask: ['Tâche ciblée : #526 - Web i18n - navigation', 'Target task: #526 - Web i18n - navigation'],
  skillAction: ['Exécution de la compétence Clarify', 'Running skill Clarify'],
  skillQueuedSummary: ["Compétence Clarify en file d'attente pour la tâche SFE-12", 'Skill Clarify queued for task SFE-12'],
  workerQueue: ["Poussée dans la file d'attente du worker...", 'Pushed to the worker queue...'],
  executionQueue: ["Poussée dans la file d'attente d'exécution...", 'Pushed to the execution queue...'],
  canceledByUser: ["Annulée par l'utilisateur", 'Canceled by the user'],
  internalFailure: ["Échec interne pendant l'exécution de la skill", 'Internal failure while running the skill'],
  engine: ['🤖 Moteur IA : CLAUDE (opus)', '🤖 AI engine: CLAUDE (opus)'],
  repositorySkill: ['📄 Skill du dépôt utilisée : .claude/skills/clarify/SKILL.md', '📄 Repository skill used: .claude/skills/clarify/SKILL.md'],
  executionError: ["⚠️ Erreur d'exécution : exit status 1", '⚠️ Execution error: exit status 1'],
  modelResponded: ['✅ Réponse générée par le modèle IA avec succès', '✅ Response generated by the AI model'],
  customCommandIn: ['Exécution de la commande personnalisée : make test dans sectile', 'Running the custom command: make test in sectile'],
  customCommand: ['Exécution de la commande personnalisée dans sectile', 'Running the custom command in sectile'],
  agentCommand: ['Exécution de : claude -p "..." dans sectile', 'Running: claude -p "..." in sectile'],
  trackerWrite: ['Écriture tracker', 'Tracker write'],
  assignAction: ['Assignation de SFE-12', 'Assigning SFE-12'],
  assignSummary: ["Assignation de SFE-12 à Jane Doe en file d'attente", 'Assignment of SFE-12 to Jane Doe queued'],
  detachAction: ['Détachement de SFE-12 de son épic', 'Detaching SFE-12 from its epic'],
  detachSummary: ["Détachement de SFE-12 en file d'attente", 'Detachment of SFE-12 queued'],
  attachAction: ['Rattachement de SFE-12 à SFE-1', 'Attaching SFE-12 to SFE-1'],
  attachSummary: ["Rattachement de SFE-12 à l'épic SFE-1 en file d'attente", 'Attachment of SFE-12 to epic SFE-1 queued'],
  epicSplitAction: ["Découpe d'épic : 3 ticket(s) ➔ SFE-9", 'Epic split: 3 ticket(s) ➔ SFE-9'],
  epicSplitSummary: ["Déplacement de 3 ticket(s) vers SFE-9 en file d'attente", 'Move of 3 ticket(s) to SFE-9 queued'],
  ticketsToMove: ['3 ticket(s) à déplacer', '3 ticket(s) to move'],
  horizonAction: ['Horizon de SFE-1 ➔ NOW', 'Horizon of SFE-1 ➔ NOW'],
  horizonSummary: ["Label d'horizon de SFE-1 en file d'attente", 'Horizon label of SFE-1 queued'],
  transitionAction: ['Transition de SFE-12 ➔ In Review', 'Transition of SFE-12 ➔ In Review'],
  transitionSummary: ["Transition de SFE-12 vers « In Review » en file d'attente", 'Transition of SFE-12 to "In Review" queued'],
  stageAction: ['Étape de #526 ➔ clarified', 'Stage of #526 ➔ clarified'],
  stageSummary: [
    "Passage de #526 à l'étape « clarified » [#clarified] en file d'attente",
    'Move of #526 to stage "clarified" [#clarified] queued',
  ],
  teamAction: ['Équipe de SFE-12 ➔ Platform', 'Team of SFE-12 ➔ Platform'],
  teamSummary: ["Changement d'équipe de 4 ticket(s) en file d'attente", 'Team change of 4 ticket(s) queued'],
  sprintAction: ['Sprint de SFE-12 ➔ Sprint 42', 'Sprint of SFE-12 ➔ Sprint 42'],
  sprintSummary: ["Changement de sprint de SFE-12 en file d'attente", 'Sprint change of SFE-12 queued'],
  horizonsPushAction: ['Horizons de roadmap ➔ labels Jira', 'Roadmap horizons ➔ Jira labels'],
  horizonsPushSummary: ["Mise à jour des labels d'horizon en file d'attente", 'Horizon label update queued'],
  horizonsPushTarget: [
    'Cible : tous les épics classés localement dont le label est absent ou obsolète',
    'Target: every locally classified epic whose label is missing or outdated',
  ],
  targetNoEpic: ['Cible : SFE-12 ➔ aucun épic', 'Target: SFE-12 ➔ no epic'],
  targetArrow: ['Cible : #526 ➔ #clarified', 'Target: #526 ➔ #clarified'],
  targetGithubRepository: ['Cible : GitHub Repository (sebastienferry/sectile)', 'Target: GitHub repository (sebastienferry/sectile)'],
  targetJiraProject: ['Cible : Jira Project (SFE)', 'Target: Jira project (SFE)'],
  target: ['Cible : backlog', 'Target: backlog'],
  targetsAll: ['Cibles : Tous les projets et trackers distants configurés', 'Targets: every configured project and remote tracker'],
  targetTrackerStatus: ['Statut tracker visé : In Progress', 'Target tracker status: In Progress'],
  pullRequest: ['Pull Request : https://github.com/o/r/pull/7', 'Pull request: https://github.com/o/r/pull/7'],
  labelUpdatedWithState: [
    '✅ Ticket github #526 mis à jour avec le label « #clarified » (état: open)',
    '✅ github ticket #526 updated with label "#clarified" (state: open)',
  ],
  labelUpdated: ['✅ Ticket github #526 mis à jour avec le label « #clarified »', '✅ github ticket #526 updated with label "#clarified"'],
  stageReportPosted: ["💬 Rapport d'étape consigné sur #526", '💬 Stage report posted on #526'],
  stageReportFailed: ["❌ Rapport d'étape non consigné sur #526 : HTTP 403", '❌ Stage report not posted on #526: HTTP 403'],
  stageReachedStep: ["✅ #526 passé à l'étape « clarified » [#clarified]", '✅ #526 moved to stage "clarified" [#clarified]'],
  stageReached: ["#526 passé à l'étape « clarified » [#clarified]", '#526 moved to stage "clarified" [#clarified]'],
  transitionedOn: ['✅ SFE-12 transitionné vers « Done » sur jira', '✅ SFE-12 transitioned to "Done" on jira'],
  transitionedStep: ['✅ SFE-12 transitionné vers « Done »', '✅ SFE-12 transitioned to "Done"'],
  transitioned: ['SFE-12 transitionné vers « Done »', 'SFE-12 transitioned to "Done"'],
  movedLocallyStep: ['✅ L-3 déplacé vers « Done » en local', '✅ L-3 moved to "Done" locally'],
  movedLocally: ['L-3 déplacé vers « Done » en local', 'L-3 moved to "Done" locally'],
  remoteSyncFailed: [
    '⚠️ Synchro distante github échouée pour #526: HTTP 502, statut gardé en local',
    '⚠️ Remote github sync failed for #526: HTTP 502, status kept locally',
  ],
  trackerTransitionFailed: [
    '⚠️ Transition tracker Done échouée (no transition), statut gardé en local',
    '⚠️ Tracker transition Done failed (no transition), status kept locally',
  ],
  assignedOn: ['✅ SFE-12 assigné à Jane Doe sur jira', '✅ SFE-12 assigned to Jane Doe on jira'],
  assigned: ['SFE-12 assigné à Jane Doe', 'SFE-12 assigned to Jane Doe'],
  unassignedOn: ['✅ SFE-12 désassigné sur jira', '✅ SFE-12 unassigned on jira'],
  unassigned: ["SFE-12 n'a plus d'assigné", 'SFE-12 has no assignee anymore'],
  assignmentKeptLocally: ['L-3 : assignation gardée en local', 'L-3: assignment kept locally'],
  detached: ['SFE-12 détaché de son épic', 'SFE-12 detached from its epic'],
  attached: ["SFE-12 rattaché à l'épic SFE-1", 'SFE-12 attached to epic SFE-1'],
  ticketsMovedTo: ['2 ticket(s) déplacé(s) vers Sprint 42', '2 ticket(s) moved to Sprint 42'],
  trackerWriteFailed: ["Échec de l'écriture sur le tracker", 'Tracker write failed'],
  failed: ['❌ Échec : 401 Unauthorized', '❌ Failed: 401 Unauthorized'],
  ticketUpdate: ['Mise à jour du ticket GitHub [#526] (sebastienferry/sectile)', 'Updating GitHub ticket [#526] (sebastienferry/sectile)'],
  targetStatusAndStage: ['Statut cible : in_progress | Étape IA : #specified', 'Target status: in_progress | AI stage: #specified'],
  syncTicketWithStage: ['Sync GitHub : #526 (#clarified)', 'Sync GitHub: #526 (#clarified)'],
  syncTicket: ['Sync Jira : SFE-12', 'Sync Jira: SFE-12'],
  asyncUpdate: ['Mise à jour asynchrone sur Jira (in_progress)', 'Asynchronous update on Jira (in_progress)'],
  runningUpdate: [
    'Exécution: mise à jour github pour #526 (statut: in_progress, labels: [#clarified ui])',
    'Running: github update for #526 (status: in_progress, labels: [#clarified ui])',
  ],
  issueUpdated: ['✅ Issue github #526 mise à jour avec succès', '✅ github issue #526 updated'],
  issueSynchronized: [
    'Issue github #526 synchronisée avec succès (Titre: Fix (again), Statut: done, Labels: [#finished])',
    'github issue #526 synchronized (Title: Fix (again), Status: done, Labels: [#finished])',
  ],
  singleSyncBack: ['Synchronisation retour unitaire (rsync local) depuis github...', 'Single-ticket sync back (local rsync) from github...'],
  rsyncPartial: ['⚠️ Rsync local partiel : timeout', '⚠️ Partial local rsync: timeout'],
  rsyncDone: [
    '✅ Rsync local terminé : état distant réaligné en base locale',
    '✅ Local rsync done: remote state realigned in the local database',
  ],
  localTaskOnly: ['ℹ️ Tâche locale uniquement, aucune commande distante requise', 'ℹ️ Local task only, no remote command needed'],
  noRemoteTracker: ['Aucun tracker distant configuré pour cette tâche', 'No remote tracker configured for this task'],
  trackerSyncFailed: ['Échec de la synchronisation tracker', 'Tracker synchronization failed'],
  remoteSync: ['Synchronisation des tickets distants', 'Remote ticket synchronization'],
  syncQueuedWithTarget: ["Synchronisation Jira (SFE) en file d'attente", 'Jira synchronization (SFE) queued'],
  multiSyncQueued: ["Synchronisation multi-trackers en file d'attente", 'Multi-tracker synchronization queued'],
  syncQueued: ["Synchronisation GitLab en file d'attente", 'GitLab synchronization queued'],
  globalSync: ['Sync Globale', 'Global sync'],
  incrementalRead: [
    'Lecture incrémentale : les tickets modifiés depuis 15 minute(s)',
    'Incremental read: tickets changed in the last 15 minute(s)',
  ],
  localWriteFailed: ['⚠️ Jira: écriture locale échouée: disk full', '⚠️ Jira: local write failed: disk full'],
  teamsFailed: ['⚠️ Équipes : HTTP 500', '⚠️ Teams: HTTP 500'],
  boardFailed: ['⚠️ Board : no board', '⚠️ Board: no board'],
  roadmapFailed: ['⚠️ Roadmap : horizons non importés : HTTP 500', '⚠️ Roadmap: horizons not imported: HTTP 500'],
  pullRequestsWriteFailed: [
    '⚠️ Pull requests #526 : écriture locale échouée : locked',
    '⚠️ Pull requests #526: local write failed: locked',
  ],
  pullRequestsAttached: ['🔗 #526 \u2014 pull request(s) rattachée(s) : #7, #8', '🔗 #526: pull request(s) attached: #7, #8'],
  pullRequestsInterrupted: [
    '⚠️ Pull requests : découverte interrompue pour cette passe',
    '⚠️ Pull requests: discovery interrupted for this pass',
  ],
  convertedAction: ['Tâche convertie vers GITHUB (#77)', 'Task converted to GITHUB (#77)'],
  remoteIssueCreated: ['Issue distante créée avec succès : #77', 'Remote issue created: #77'],
  creatingRemoteTicket: ['Création du ticket distant sur GITHUB', 'Creating the remote ticket on GITHUB'],
  updatingKey: ['Mise à jour de la clé (#77) et de la source', 'Updating the key (#77) and the source'],
  postBackAction: ['Post-back local', 'Local post-back'],
  postBackFailed: ['Échec post-back tracker: 404', 'Tracker post-back failed: 404'],
  postBackError: ['❌ Erreur post-back: 404', '❌ Post-back error: 404'],
  specInstall: ['Installation de Spec Kit dans /srv/sectile', 'Installing Spec Kit in /srv/sectile'],
  specAlreadyInitialized: ['⏭️ Déjà initialisé, aucune commande exécutée', '⏭️ Already initialized, no command run'],
}

test('every server template has a sample, and every sample names a template', () => {
  const keys = Object.keys(operations.fr.activityTemplates).sort()
  assert.deepEqual(Object.keys(SAMPLES).sort(), keys)
})

for (const [key, [french, english]] of Object.entries(SAMPLES)) {
  test(`template ${key}: recognized, rendered in English, unchanged in French`, () => {
    assert.equal(matchActivityTemplate(french)?.key, key)
    assert.equal(localizeActivityText(french, 'en'), english)
    assert.equal(localizeActivityText(french, 'fr'), french)
  })
}

test('the spec examples render as specified', () => {
  assert.equal(localizeActivityText("Exécution de clarify sur l'agent local", 'en'), 'Running clarify on the local agent')
  assert.equal(localizeActivityText('Tâche ciblée : #526 - Title', 'en'), 'Target task: #526 - Title')
})

test('text no template matches is returned unchanged in both languages', () => {
  for (const text of [
    '## Clarification report\n\nAll good.',
    'fatal: not a git repository (or any of the parent directories): .git',
    'npm run build && npm test',
    'Execution reported by a local agent or native client',
    // A known template with extra text is not that template: matching is anchored.
    "Exécution de clarify sur l'agent local, puis autre chose",
    "Préfixe Annulée par l'utilisateur",
    '',
  ]) {
    assert.equal(localizeActivityText(text, 'en'), text)
    assert.equal(localizeActivityText(text, 'fr'), text)
  }
})

test('parameters holding regex characters or placeholders are kept verbatim', () => {
  const key = 'a.b*c+(d)?[e]{0}$^|\\'
  assert.equal(localizeActivityText(`Tâche ciblée : ${key} - {1} title`, 'en'), `Target task: ${key} - {1} title`)
  assert.equal(localizeActivityText(`Cible : ${key}`, 'en'), `Target: ${key}`)
})

test('a parameter spanning several lines is still one parameter', () => {
  assert.equal(localizeActivityText('❌ Échec : line one\nline two', 'en'), '❌ Failed: line one\nline two')
})

test('the more specific template wins over a general one', () => {
  assert.equal(matchActivityTemplate('Cible : SFE-1 ➔ aucun épic')?.key, 'targetNoEpic')
  assert.equal(matchActivityTemplate('Cible : SFE-1 ➔ SFE-2')?.key, 'targetArrow')
  assert.equal(matchActivityTemplate('Cible : SFE-1')?.key, 'target')
  assert.equal(matchActivityTemplate("✅ #1 passé à l'étape « new » [#new]")?.key, 'stageReachedStep')
})

test('a template compiles to an anchored pattern with escaped literals', () => {
  const pattern = templatePattern('Cible : {0} (x.y)')
  assert.ok(pattern.test('Cible : A (x.y)'))
  assert.ok(!pattern.test('Cible : A (xzy)'))
  assert.ok(!pattern.test('> Cible : A (x.y)'))
})
